### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by aperezva** [eavanvalkenburg/pysiaalarm#25]
I m sorry but I don´t have knowledge in programming etc. I have Ajax alarm with different sensors and in differents rooms. I use three alarm methods, one full activation, another night  and another a partical activation.

Also I have two smoke sensors and two water detectors.

Please could you help me how to integrate all this devices and methods?

Thanks

**Comment by aperezva** [comment]
Hi Eduard,

Alrm working fine thanks a lot.

Only one question, I have two water detecter and wo smoke detector, How can I configure them? They are in the different rooms. Now I have only two detected or configured. How can I difference between each other?

Thanks

**Comment by eavanvalkenburg** [comment]
Good to hear the alarm works! The SIA protocol doesn't distinguish between different sensors unless they are in different zones, then if you setup the integration with those zones you get them (and also a alarm for the other zone, because SIA doesn't tell me what is in a zone, so I just create a alarm, water and smoke in each), so just enable/disable the ones you want!
