### ISSUE TITLE
Sia alarm integration not working with 2022.7 version

### ISSUE THREAD

**Issue by aperezva** [eavanvalkenburg/pysiaalarm#31]
It seems las upgrade affects SIA integration and comunication between my Ajax alarm and home assistant is not working

any idea how to solve the problem?

**Comment by aperezva** [comment]
Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for sia using this method at custom_components/sia/hub.py, line 95: device_registry = await dr.async_get_registry(self._hass)
07:05:29 – (ADVERTENCIA) helpers/frame.py

**Comment by eavanvalkenburg** [comment]
Hi @aperezva this custom integration is no longer maintained, so make sure you use the official integration, there was no change in 2022.7 so please turn on logging and create an issue with logs in the core repo since that is where I can easily link it if it requires a fix and also has all the fields for an issue. Finally if you are using ajax systems make sure to include the version of OS Malevich since I've previously had a report that their latest update caused encrypted sia to fail, so you can also try disabling encryption on both systems.

**Comment by aperezva** [comment]
Thanks

Fixed

I didn’t know regarding official integration

Changed and everything is working

BR

**Comment by eavanvalkenburg** [comment]
Thanks for reporting back!
